# Generated by Django 5.1.7 on 2025-04-20 14:12

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("doctor", "0010_doctormodel_gender"),
    ]

    operations = [
        migrations.CreateModel(
            name="DoctorChat",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("text", models.TextField()),
                (
                    "created_at",
                    models.DateTimeField(
                        default=datetime.datetime(2025, 4, 20, 7, 12, 13, 977789)
                    ),
                ),
                (
                    "reciever",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reciever",
                        to="doctor.doctormodel",
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sender_object",
                        to="doctor.doctormodel",
                    ),
                ),
            ],
        ),
    ]
