# Generated by Django 5.1.7 on 2025-04-28 18:46

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0001_initial"),
        ("doctor", "0010_doctormodel_gender"),
    ]

    operations = [
        migrations.AlterField(
            model_name="doctorchat",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 4, 28, 11, 46, 42, 144979)
            ),
        ),
        migrations.CreateModel(
            name="DoctorChatRoom",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "created_at",
                    models.DateTimeField(
                        default=datetime.datetime(2025, 4, 28, 11, 46, 42, 144979)
                    ),
                ),
                (
                    "firstTerminal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="FirstTerminal",
                        to="doctor.doctormodel",
                    ),
                ),
                (
                    "secondTerminal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="SecondTerminal",
                        to="doctor.doctormodel",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="doctorchat",
            name="ChatRoom",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="Room",
                to="chat.doctorchatroom",
            ),
        ),
    ]
