# Generated by Django 5.1.7 on 2025-04-30 06:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0002_alter_doctorchat_created_at_doctorchatroom_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="doctorchat",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 4, 29, 23, 7, 8, 416758)
            ),
        ),
        migrations.AlterField(
            model_name="doctorchatroom",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 4, 29, 23, 7, 8, 416758)
            ),
        ),
    ]
