# Generated by Django 5.1.7 on 2025-04-30 06:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0003_alter_doctorchat_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="doctorchat",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 4, 29, 23, 15, 23, 773937)
            ),
        ),
        migrations.AlterField(
            model_name="doctorchatroom",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 4, 29, 23, 15, 23, 773436)
            ),
        ),
    ]
