# Generated by Django 5.1.7 on 2025-05-04 09:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0005_alter_doctorchat_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="doctorchat",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 5, 4, 2, 20, 10, 579653)
            ),
        ),
        migrations.AlterField(
            model_name="doctorchatroom",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 5, 4, 2, 20, 10, 579653)
            ),
        ),
    ]
