# Generated by Django 5.1.7 on 2025-05-04 16:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0006_alter_doctorchat_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="doctorchat",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 5, 4, 9, 51, 31, 361103)
            ),
        ),
        migrations.AlterField(
            model_name="doctorchatroom",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 5, 4, 9, 51, 31, 360618)
            ),
        ),
    ]
