# Generated by Django 5.1.7 on 2025-03-19 19:30

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DoctorModel",
            fields=[
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.TextField()),
                ("email", models.EmailField(max_length=32)),
                ("address", models.TextField()),
                ("password", models.TextField()),
                ("phone", models.TextField()),
                ("graduate_date", models.DateField()),
                (
                    "certificate_file",
                    models.FileField(upload_to="doctor/file/certificated"),
                ),
                (
                    "personal_image",
                    models.ImageField(upload_to="doctor/file/perosnal_image"),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
