# Generated by Django 5.1.7 on 2025-03-20 07:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("doctor", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="doctormodel",
            name="email",
            field=models.EmailField(max_length=32, unique=True),
        ),
    ]
