# Generated by Django 5.1.7 on 2025-03-20 08:46

import doctor.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("doctor", "0002_alter_doctormodel_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="doctormodel",
            name="certificate_file",
            field=models.FileField(
                upload_to="doctor/file/certificated",
                validators=[doctor.models.validate_pdf],
            ),
        ),
        migrations.AlterField(
            model_name="doctormodel",
            name="personal_image",
            field=models.ImageField(
                upload_to="doctor/file/perosnal_image",
                validators=[doctor.models.validate_image],
            ),
        ),
    ]
