# Generated by Django 5.1.7 on 2025-03-23 08:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("doctor", "0003_alter_doctormodel_certificate_file_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DoctorNotification",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("text", models.TextField()),
                ("is_read", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("target_url", models.URLField(null=True)),
                ("sender_id", models.IntegerField(null=True)),
                ("model", models.CharField(default="doctor", max_length=50)),
                (
                    "doctor_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="doctor.doctormodel",
                    ),
                ),
            ],
        ),
    ]
