# Generated by Django 5.1.7 on 2025-03-23 09:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("doctor", "0004_doctornotification"),
    ]

    operations = [
        migrations.CreateModel(
            name="symptom",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=50)),
                (
                    "doctor_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="doctor.doctormodel",
                    ),
                ),
                (
                    "symptom_parent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="doctor.symptom"
                    ),
                ),
            ],
        ),
    ]
