# Generated by Django 5.1.7 on 2025-03-23 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("doctor", "0005_symptom"),
    ]

    operations = [
        migrations.AlterField(
            model_name="symptom",
            name="symptom_parent",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="doctor.symptom",
            ),
        ),
    ]
