# Generated by Django 5.1.7 on 2025-04-09 07:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("doctor", "0006_alter_symptom_symptom_parent"),
    ]

    operations = [
        migrations.CreateModel(
            name="certificate",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.TextField()),
                ("status", models.BooleanField(default=False)),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="doctor.doctormodel",
                    ),
                ),
            ],
        ),
    ]
