# Generated by Django 5.1.7 on 2025-04-09 10:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("doctor", "0008_certificate_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="certificate",
            name="certified_at",
            field=models.DateField(default=datetime.date.today),
        ),
    ]
