# Generated by Django 5.1.7 on 2025-04-12 08:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("doctor", "0009_certificate_certified_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctormodel",
            name="gender",
            field=models.CharField(default="male", max_length=10),
        ),
    ]
