# Generated by Django 5.1.7 on 2025-03-20 08:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="patient",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.TextField()),
                ("email", models.EmailField(max_length=254)),
                ("password", models.TextField(null=True)),
                ("address", models.TextField()),
                ("phone", models.TextField()),
                ("birth_date", models.DateField()),
                ("Register_date", models.DateField(default=datetime.date.today)),
                ("job", models.TextField()),
            ],
        ),
    ]
