# Generated by Django 5.1.7 on 2025-03-22 11:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("doctor", "0003_alter_doctormodel_certificate_file_and_more"),
        ("patients", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="doctor",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="doctor.doctormodel",
            ),
        ),
    ]
