# Generated by Django 5.1.7 on 2025-03-23 09:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("doctor", "0005_symptom"),
        ("patients", "0002_patient_doctor"),
    ]

    operations = [
        migrations.CreateModel(
            name="patient_suffer",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "patient_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="patients.patient",
                    ),
                ),
                (
                    "symptom_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="doctor.symptom"
                    ),
                ),
            ],
        ),
    ]
