# Generated by Django 5.1.7 on 2025-03-26 11:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("patients", "0003_patient_suffer"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient_suffer",
            name="symptoms",
            field=models.JSONField(default=list),
        ),
    ]
