# Generated by Django 5.1.7 on 2025-03-28 15:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("doctor", "0006_alter_symptom_symptom_parent"),
        ("patients", "0004_patient_suffer_symptoms"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient_suffer",
            name="diagnosed_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="doctor.doctormodel",
            ),
        ),
    ]
