# Generated by Django 5.1.7 on 2025-04-09 07:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("patients", "0005_patient_suffer_diagnosed_by"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patient_suffer",
            name="created_at",
            field=models.DateTimeField(default=datetime.date.today),
        ),
    ]
