# Generated by Django 5.1.7 on 2025-04-10 20:06

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("doctor", "0009_certificate_certified_at"),
        ("patients", "0006_alter_patient_suffer_created_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="patientNotes",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("text", models.TextField()),
                ("created_at", models.DateField(default=datetime.date.today)),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="doctor.doctormodel",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="patients.patient",
                    ),
                ),
            ],
        ),
    ]
