# Generated by Django 5.1.7 on 2025-04-30 06:07

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("doctor", "0010_doctormodel_gender"),
        ("patients", "0007_patientnotes"),
    ]

    operations = [
        migrations.CreateModel(
            name="allowedTo",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("allowed", models.TextField(default="__read__")),
                ("created_at", models.DateField(default=datetime.date.today)),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="doctor.doctormodel",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="patients.patient",
                    ),
                ),
            ],
        ),
    ]
