# Generated by Django 5.1.7 on 2025-05-04 09:20

import datetime
import django.db.models.deletion
import patients.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("patients", "0009_allowedto_patient_approved"),
    ]

    operations = [
        migrations.CreateModel(
            name="patient_media",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "file",
                    models.FileField(
                        upload_to="patient/media/",
                        validators=[patients.models.validate_size],
                    ),
                ),
                ("created_at", models.DateField(default=datetime.date.today)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="patients.patient",
                    ),
                ),
            ],
        ),
    ]
