# Generated by Django 5.1.7 on 2025-05-04 16:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("patients", "0010_patient_media"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient_media",
            name="file_type",
            field=models.TextField(default=None),
        ),
    ]
